version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: supersecretpassword
      WORDPRESS_DB_NAME: wordpress
    networks:
      - frontend
      - backend


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: wordpress
    networks:
      - backend

networks:
  frontend:
  backend:
    internal: true
